#ifndef INTERACTION_COMBINATORS_H
#define INTERACTION_COMBINATORS_H

#define IC_PROJECT_NAME "interaction_combinators"
#define IC_VERSION_MAJOR 0
#define IC_VERSION_MINOR 2
#define IC_VERSION_PATCH 0
#define IC_VERSION_STRING "0.2.0"

#endif /* INTERACTION_COMBINATORS_H */


